### PR TITLE
PR#44_RB_v0.94.02  chance to take the bug-fixes made so far

### PR DESCRIPTION
**Pull request by DF4IAH**
This pull request gives the RedPitaya team a chance to get all the bug-fixes made for Red-Pitaya, which were made by developing the DF4IAH/RedPitaya_RadioBox spin-off.

It is based on RedPitaya's 106c6e6e0498d421c92e55e1dc456a596de13d0d  
that was updated here on GitHub on 2015-12-18.

The main features for RedPitaya:
- running the CPU-cores @ 666.667 MHz instead of 500 MHz
- activating and streaming the XADC data for easy access
- libstdc++.so problem on target fixed
- many corrections on Makefiles made

- testest on Ubuntu-Linux as well as (part of) in WIndows-7.

Feel free to get that chance or drop it - it is in your hand.

For future updates here in GitHub it would be fine not to brake the history of the repository. 
Due to that I had to rework all my stuff again.

Cheers
  Uli, DF4IAH

### CODE REVIEW

**Comment by jeras** [comment]
Thanks Ulrich,

This will take a lot of time to process. I will inform you while we progress. I already did some unpublished FPGA changes, so I expect many conflicts there.

**Comment by jeras** [comment]
I would be glad, if you could organize this changes into groups, each fixing an issue or adding a feature. It is annoying to merge code, where there are buggy commits which are later reverted.

But you probably do not have much time, so I would like to at least discuss some of the changes before I merge them.

Why did you add project files, I spent some effort removing them, since they put a lot of redundant code into git. In any case it is not good practice to add generated (not intentionally ceded) files. I know that the current project created from system.tcl files for system.bd, has many issues. Some have been fixed in Vivado 2015.3, so there is (will be) no need to upload system.bd. Are there any other features which only work properly if project files are provided?

Regarding migration to Vivado 2015.3, I would like to migrate U-Boot and the Linux kernel at the same time. I was able to port all U-Boot patches, but we have issues with the kernel. I still did not have the time to debug why SPI is not working and with newer kernels we also had USB (not working at all) and Ethernet (complaining about some code in the Lantiq patch) issues.

Replacing curl with wget is fine, especially if this improves compatibility with another development environment. I plan to change the download directory into the current folder by default, I did not do it yet, since our nightly builds rely on the current setup.

Regarding streaming support for XADC, could you explain what had to be changed, and how does it fit into the IIO Linux driver.

Regarding RadioBox, could you explain what were the required FPGA changes, and did you plan to build a separate bitstream for it?

The libstdc++.so and Makefile changes are very appreciated, but I have a hard time finding them among everything else.

Regarding CPU clocking changes, I plan to review all PS clocks, especially to see if I can improve SD card interface performance. But as you already know, I did not yet have the time to look into it...


Yes, the history breakage. Some of our code is now closed source, but still part of our internal repo. So I had to remove this code from Git history. It was either this or postponing the release. I can handle git well, but not well enough to make everybody happy. I will definitely try, but can not promise, this will not happen again.

**Comment by HrRossi** [comment]
First, I have to say, thanks @DF4IAH , there are some nice findings among the changes. 
I'm currently cherry-picking low-risk changes and incorporating them into my fork. If it's ok for both of you, I'll issue small-scale PRs from there, though the credits for the work go to Uli, of course.

**Comment by HrRossi** [comment]
@jeras the PS clocks have been near optimal in 0.93 . You wont get more performance out of the sd-card, because it is already clocked at its maximum (50MHz controller clock from the 100MHz base clock). That the processor is running at 500MHz is just a small bug. I'll do the PR for that first.

**Comment by DF4IAH** [comment]
Hello,
sorry to tell that I am really busy at the moment - also catched a flu. Hopefully after chrismas I find more time to go into the details mentioned so far.

Here a short answer list to the questions:
- CPU 666 MHz:
  I found out, that the clocking source for the ETH-interface was based on the CPU clock, not the IO-PLL. After switching this the processor-cores got their 666 MHz. I have nothing changed to the frequencies of the other parts within the BD.
- I decided to take the XADC to 125 MHz, also. I activated the AXA-S streaming interface, that ends (at the moment) in the radiobox sub-module updating its channel registers. The XADC runs fine with 48 kSPS with 16 samples for smoothing. I think the XADC channels are perfect for audio in and out solutions. The XADC is configured to have 2x stereo sampled. Each stereo channel is sampled at the same time w/o delay to each other for phase=0° purposes.
- I have added more IRQ-lines to the IRQ S-->P direction to make it easier for working on the FPGA without touching the BD internals, what would need a complete build to craft a boot image / loader, since the core-block can not be modified after boot-up.
- Thanks for the credits!
- Well, about the project files: Within the system-BD I am trusting fully to write out the TCL-script, what works very fine, indeed. For external blocks I rely on the high fidelity IPs with high performance against small footprint. The device mapper does not make such good decissions, thats why the engineers of Xilinx have developped such IPs. When writing out __THAT__ complete project TCL-Script, in the header section you will find a notice about the files to be saved seperatly. That is exactly what I have done. Between Vivado 2015.3 and 2015.4 I can see a move from the *.xci to *.xcix files, that are binary instead of plain XML what results to bigger data clusters to be stored within the GIT repository. Well, that is something I do not really like to which direction Xilinx is heading to.

At the momemt I am fiddling around to have a small footprint for the SSB (single-sideband-modulation) - but it is worth the time I need for that, and makes much fun to have a fully working transceiver just in that FPGA with all features of the other applications not distorting anything. So if you load my __fpga_rb-xxxxx_v0.94.bit__  files you can run all other stuff. At the moment I have nothing removed so far. DSP usage is just litte more than 50% now with much potential to have it at lower levels when it is needed to.

All right, I think I find some more time on christmas to be more precise what the RadioBox extension can do for you.

At the moment you have an oscillator with modulating features (internal and external): some guys told me that this is already that, what they were looking for a long time missing at the RedPitaya system. Knowing that helps me for planing ahead the next features. A nice web-frontend would be nice, also. Anyone loving to design one?

Cheers
  Uli, DF4IAH

**Comment by jeras** [comment]
Yesterday I fixed an issue we had with USB on Xilinx kernels from 2015.2 on, so now I have a working image using Vivado 2015.4 and the related kernel, U-Boot and devicetree. We do not plan to merge it into master right now (probably in two weeks), since we did not test it much yet, but I will probably publish it on a branch on GitHub.

**Comment by DF4IAH** [comment]
A new version RB_v0.94.03 is ready for a PR. See #48 for details.

I would recommend closing this PR.

Thanks and have a pleasant happy new year 2016!

Yours
  Ulrich Habel, DF4IAH

**Pull request closed without merging**
